refs #000: Add feature backendconfig and add config ssl-redirect
sparkfabrik/terraform-helm-ingress-nginx pull request #8
Opened 2023-12-21 17:01 UTC by filippolmt

2023-12-21 17:11 UTC, nbucci approved these changes

2023-12-21 17:11 UTC, Monska85 requested changes

2023-12-21 17:11 UTC, Monska85 commented on CHANGELOG.md
> +- Feature: add requests in `defaultBackend`
```suggestion
- Feature: add requests in `defaultBackend`.
```

2023-12-21 17:18 UTC, Monska85 commented on CHANGELOG.md
> +### Changed
```suggestion
## [0.4.0] - 2023-12-21

[Compare with previous version](https://github.com/sparkfabrik/terraform-helm-ingress-nginx/compare/0.3.0...0.4.0)

### Changed

- Feature: add `ssl-redirect` configuration.
- Feature: add requests in `defaultBackend`.

```

2023-12-22 09:14 UTC, Monska85 approved these changes
LGTML :+1:

2023-12-22 09:18 UTC, merged